on:
  push:
    branches:
      - main
      - master
      - dev
env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: 17
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Prepare Gradle
        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc
      - name: fix permission error
        run: chmod +x gradlew
      - name: 📦 package Windows app
        run: ./gradlew packageJvmWindowsApp
